import React, { createContext, useState, useContext } from 'react';

const translations = {
  en: {
    guitarBrands: 'Guitar Brands',
    guitarModels: 'Guitar Models',
    searchByName: 'Search by name',
    filterByType: 'Filter by type',
    specs: 'Specifications',
    musicians: 'Musicians',
    showMore: 'Show more',
    loading: 'Loading...',
    error: 'Error fetching data',
    english: 'English',
    macedonian: 'Macedonian',
    albanian: 'Albanian',
    browseTopQuality: 'Browse top quality',
    guitars: 'Guitars',
    online: 'online',
    exploreCollections: 'Explore 50k+ latest collections of branded guitars online with VibeStrings.',
    featuring: 'Featuring the',
    bestBrands: 'Best Brands',
    selectPreferredBrand: 'Select your preferred brand and explore our exquisite collection.',
    priceUnavailable: 'Price unavailable',
    vibeStringsLogo: 'VibeStrings Logo',
    contactEmail: 'Enquiry@VibeStrings.com',
    location: 'San Francisco',
    pages: 'PAGES',
    store: 'Store',
    collections: 'Collections',
    support: 'Support',
    product: 'PRODUCT',
    terms: 'Terms',
    privacy: 'Privacy Policy',
    copyright: 'Copyright',
    followUs: 'FOLLOW US',
    language: 'Language',
    vibeStrings: 'VibeStrings',
    priceUnavailable: 'Price unavailable',
    checkSelection: 'Check out the selection',
    playLikeARockstar: 'Play like a Rock Star',
    description: 'Description',
    brandHistory: 'Brand History',
    specifications: 'Specifications',
    players: 'Players',
  },
  mk: {
    guitarBrands: 'Брендови на гитари',
    guitarModels: 'Модели на гитари',
    searchByName: 'Пребарување по име',
    filterByType: 'Филтрирај по тип',
    specs: 'Спецификации',
    musicians: 'Музичари',
    showMore: 'Погледни повеќе',
    loading: 'Се вчитува...',
    error: 'Грешка при преземање на податоци',
    english: 'Англиски',
    macedonian: 'Македонски',
    albanian: 'Албански',
    browseTopQuality: 'Барајте врвен квалитет',
    guitars: 'Гитари',
    online: 'онлајн',
    exploreCollections: 'Истражете 50k+ најнови колекции на брендови гитари онлајн со VibeStrings.',
    featuring: 'Претставувајќи ги',
    bestBrands: 'Најдобрите брендови',
    selectPreferredBrand: 'Изберете го вашиот омилен бренд и истражете ја нашата колекција.',
    priceUnavailable: 'Цена недостапна',
    vibeStringsLogo: 'VibeStrings Лого',
    contactEmail: 'Enquiry@VibeStrings.com',
    location: 'Сан Франциско',
    pages: 'ПАГИНИ',
    store: 'Продавница',
    collections: 'Колекции',
    support: 'Поддршка',
    product: 'ПРОИЗВОД',
    terms: 'Услови',
    privacy: 'Политика на приватност',
    copyright: 'Авторски права',
    followUs: 'СЛЕДЕТЕ НЕ',
    language: 'Јазик',
    vibeStrings: 'VibeStrings',
    priceUnavailable: 'Цена недостапна',
    checkSelection: 'Погледни ја селекцијата',
    playLikeARockstar: 'Играј како рок sтар',
    description: 'Опис',
    brandHistory: 'Историја на брендот',
    specifications: 'Спецификации',
    players: 'Музичари',
  },
  sq: {
    guitarBrands: 'Marka të Gitarës',
    guitarModels: 'Modele të Gitarës',
    searchByName: 'Kërko sipas emrit',
    filterByType: 'Filtro sipas llojit',
    specs: 'Specifikime',
    musicians: 'Muzikantë',
    showMore: 'Trego më shumë',
    loading: 'Duke u ngarkuar...',
    error: 'Gabim gjatë marrjes së të dhënave',
    english: 'Anglisht',
    macedonian: 'Maqedonisht',
    albanian: 'Shqip',
    browseTopQuality: 'Shfletoni kualitet të lartë',
    guitars: 'Gitare',
    online: 'online',
    exploreCollections: 'Eksploroni 50k+ koleksione të fundit të gitareve të markës online me VibeStrings.',
    featuring: 'Duke prezantuar',
    bestBrands: 'Markat më të mira',
    selectPreferredBrand: 'Zgjidhni markën tuaj të preferuar dhe eksploroni koleksionin tonë.',
    priceUnavailable: 'Çmimi nuk është i disponueshëm',
    vibeStringsLogo: 'Logo e VibeStrings',
    contactEmail: 'Enquiry@VibeStrings.com',
    location: 'San Francisco',
    pages: 'FAQE',
    store: 'Dyqan',
    collections: 'Koleksione',
    support: 'Mbështetje',
    product: 'PRODUKT',
    terms: 'Kushtet',
    privacy: 'Politika e Privatësisë',
    copyright: 'E drejta e autorit',
    followUs: 'NA NDIQNI',
    language: 'Gjuha',
    vibeStrings: 'VibeStrings',
    priceUnavailable: 'Çmimi nuk është i disponueshëm',
    checkSelection: 'Shiko seleksionin',
    playLikeARockstar: 'Luaj si një Rock Star',
    description: 'Përshkrimi',
    brandHistory: 'Historia e markës',
    specifications: 'Specifikime',
    players: 'Muzikantë',
  },
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');
  const t = (key) => translations[language][key] || key;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
